In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [17]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [18]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [22]:
import pandas as pd
import numpy as np

In [36]:
df =pd.DataFrame(data = dataset.data,columns=dataset.feature_names)

In [37]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [38]:
df['target'] = dataset.target

In [65]:
df_copy = df[df['target']!=2]

In [69]:
## independent and dependent data
X = df_copy.drop('target',axis=1) # df_copy.iloc[:,:,-1] can be used
y = df_copy['target'] # df_copy.iloc[:,-1] can be used 

In [72]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [74]:
from sklearn.linear_model import LogisticRegression

In [76]:
classification = LogisticRegression(max_iter=200)

In [77]:
classification.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [78]:
y_pred = classification.predict(X_test)

In [79]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

# Confusion matrix, accuracy and classification report

In [80]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [82]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [83]:
print(accuracy_score(y_test,y_pred))

1.0


In [84]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Cross Validation

In [86]:
from sklearn.model_selection import KFold

In [87]:
cv = KFold(n_splits=5)

In [88]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [89]:
from sklearn.model_selection import cross_val_score

In [90]:
score = cross_val_score(classification,X_train,y_train,cv=cv)

In [91]:
score

array([1., 1., 1., 1., 1.])

In [94]:
print(np.mean(score))

1.0


In [95]:
## Lets see for complex dataset

In [102]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
X,y = make_classification(n_samples = 1000,n_features = 10,n_informative=5, n_redundant=5,n_classes=2,random_state=1)

In [103]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [104]:
complex_classification = LogisticRegression(max_iter=200)

In [105]:
complex_classification.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [106]:
y_pred_complex = complex_classification.predict(X_test)

In [107]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [108]:
## Cross validation 
from sklearn.model_selection import KFold
cv = KFold(n_splits=5)

In [110]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(complex_classification,X_train,y_train,cv=cv)
score

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [111]:
np.mean(score)

0.8099999999999999